[features]
seeds = false
skip-lint = false
[programs.localnet]
nft_lend_borrow = "539Cu2TavqmTpqW6yueREntmM5vetHKDGLsgu2c9FXCG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/almei/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
